print("\n--- Registro de Datos Personales ---")
nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = input("Ingrese su edad: ")
direccion = input("Ingrese su dirección: ")
telefono = input("Ingrese su número de teléfono: ")
genero = input("Ingrese su género: ")

print("\n--- Datos Ingresados ---")
print(f"Nombre: {nombre}")
print(f"Apellido: {apellido}")
print(f"Edad: {edad}")
print(f"Dirección: {direccion}")
print(f"Teléfono: {telefono}")
print(f"Género: {genero}")
